// Code generated by "stringer -trimprefix EventType -type EventType -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeMmap-1]
	_ = x[EventTypeLost-2]
	_ = x[EventTypeComm-3]
	_ = x[EventTypeExit-4]
	_ = x[EventTypeThrottle-5]
	_ = x[EventTypeUnthrottle-6]
	_ = x[EventTypeFork-7]
	_ = x[EventTypeRead-8]
	_ = x[EventTypeSample-9]
	_ = x[EventTypeMmap2-10]
	_ = x[EventTypeAux-11]
	_ = x[EventTypeItraceStart-12]
	_ = x[EventTypeLostSamples-13]
	_ = x[EventTypeSwitch-14]
	_ = x[EventTypeSwitchCPUWide-15]
	_ = x[EventTypeNamespaces-16]
	_ = x[EventTypeKsymbol-17]
	_ = x[EventTypeBPFEvent-18]
	_ = x[EventTypeCgroup-19]
	_ = x[EventTypeTextPoke-20]
	_ = x[EventTypeAuxOutputHWID-21]
	_ = x[EventTypeHeaderAttr-64]
	_ = x[EventTypeHeaderEventType-65]
	_ = x[EventTypeHeaderTracingData-66]
	_ = x[EventTypeHeaderBuildID-67]
	_ = x[EventTypeFinishedRound-68]
	_ = x[EventTypeIDIndex-69]
	_ = x[EventTypeAuxtraceInfo-70]
	_ = x[EventTypeAuxtrace-71]
	_ = x[EventTypeAuxtraceError-72]
	_ = x[EventTypeThreadMap-73]
	_ = x[EventTypeCPUMap-74]
	_ = x[EventTypeStatConfig-75]
	_ = x[EventTypeStat-76]
	_ = x[EventTypeStatRound-77]
	_ = x[EventTypeEventUpdate-78]
	_ = x[EventTypeTimeConv-79]
	_ = x[EventTypeHeaderFeature-80]
	_ = x[EventTypeCompressed-81]
	_ = x[EventTypeFinishedInit-82]
}

const (
	_EventType_name_0 = "MmapLostCommExitThrottleUnthrottleForkReadSampleMmap2AuxItraceStartLostSamplesSwitchSwitchCPUWideNamespacesKsymbolBPFEventCgroupTextPokeAuxOutputHWID"
	_EventType_name_1 = "HeaderAttrHeaderEventTypeHeaderTracingDataHeaderBuildIDFinishedRoundIDIndexAuxtraceInfoAuxtraceAuxtraceErrorThreadMapCPUMapStatConfigStatStatRoundEventUpdateTimeConvHeaderFeatureCompressedFinishedInit"
)

var (
	_EventType_index_0 = [...]uint8{0, 4, 8, 12, 16, 24, 34, 38, 42, 48, 53, 56, 67, 78, 84, 97, 107, 114, 122, 128, 136, 149}
	_EventType_index_1 = [...]uint8{0, 10, 25, 42, 55, 68, 75, 87, 95, 108, 117, 123, 133, 137, 146, 157, 165, 178, 188, 200}
)

func (i EventType) String() string {
	switch {
	case 1 <= i && i <= 21:
		i -= 1
		return _EventType_name_0[_EventType_index_0[i]:_EventType_index_0[i+1]]
	case 64 <= i && i <= 82:
		i -= 64
		return _EventType_name_1[_EventType_index_1[i]:_EventType_index_1[i+1]]
	default:
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
