// Code generated by "stringer -trimprefix hdr -type hdrType -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[hdrTracingData-1]
	_ = x[hdrBuildID-2]
	_ = x[hdrHostname-3]
	_ = x[hdrOSRelease-4]
	_ = x[hdrVersion-5]
	_ = x[hdrArch-6]
	_ = x[hdrNrCPUs-7]
	_ = x[hdrCPUDesc-8]
	_ = x[hdrCPUID-9]
	_ = x[hdrTotalMem-10]
	_ = x[hdrCmdline-11]
	_ = x[hdrEventDesc-12]
	_ = x[hdrCPUTopology-13]
	_ = x[hdrNUMATopology-14]
	_ = x[hdrBranchStack-15]
	_ = x[hdrPMUMappings-16]
	_ = x[hdrGroupDesc-17]
	_ = x[hdrAuxTrace-18]
	_ = x[hdrStat-19]
	_ = x[hdrCache-20]
	_ = x[hdrSampleTime-21]
	_ = x[hdrSampleTopology-22]
	_ = x[hdrClockID-23]
	_ = x[hdrDirFormat-24]
	_ = x[hdrBPFProgInfo-25]
	_ = x[hdrBPFBTF-26]
	_ = x[hdrCompressed-27]
	_ = x[hdrCPUPMUCaps-28]
	_ = x[hdrClockData-29]
	_ = x[hdrHybridTopology-30]
	_ = x[hdrPMUCaps-31]
	_ = x[hdrMax-32]
}

const _hdrType_name = "tracing databuild idhostnameOS releaseversionarchnum CPUsCPU descCPUIDtotal memcmdlineevent descCPU topologyNUMA topologybranch stackPMU mappingsgroup descauxstatcachesample timesample topologyclock IDdir formatBPF prog infoBPF BTFcompressedCPU PMU capsclock datahybrid topologyPMU capsMax"

var _hdrType_index = [...]uint16{0, 12, 20, 28, 38, 45, 49, 57, 65, 70, 79, 86, 96, 108, 121, 133, 145, 155, 158, 162, 167, 178, 193, 201, 211, 224, 231, 241, 253, 263, 278, 286, 289}

func (i hdrType) String() string {
	i -= 1
	if i >= hdrType(len(_hdrType_index)-1) {
		return "hdrType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _hdrType_name[_hdrType_index[i]:_hdrType_index[i+1]]
}
